name: Deploy documentation
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docs:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly 
          override: true
      - name: Setup LLVM & Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: 11.0
          directory: ${{ runner.temp }}/llvm-11.0
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: latest
      - name: Build guide
        run: mdbook build guide
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: guide/book
          CLEAN: true